In [6]:
import yfinance as yf
import pandas as pd

In [2]:

FC_F = yf.Ticker("GC=F")
hist = FC_F.history(period="max")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2000-08-30,273.899994,273.899994,273.899994,273.899994,0,0,0
2000-08-31,274.799988,278.299988,274.799988,278.299988,0,0,0
2000-09-01,277.000000,277.000000,277.000000,277.000000,0,0,0
2000-09-05,275.799988,275.799988,275.799988,275.799988,2,0,0
2000-09-06,274.200012,274.200012,274.200012,274.200012,0,0,0
...,...,...,...,...,...,...,...
2022-06-17,1853.699951,1853.699951,1833.599976,1835.599976,170,0,0
2022-06-21,1835.300049,1838.599976,1830.099976,1834.599976,216,0,0
2022-06-22,1829.500000,1842.699951,1821.599976,1834.300049,115,0,0
2022-06-23,1835.500000,1841.199951,1825.699951,1825.699951,9,0,0
2022-06-24,1824.199951,1833.699951,1817.699951,1828.099976,134283,0,0

In [17]:
df = pd.read_csv("_meta.txt")
df

   Symbol                             Name
0    NQ=F                       Nasdaq 100
1   RTY=F  E-mini Russell 2000 Index Futur
2    ZB=F       U.S. Treasury Bond Futures
3    ZN=F           10-Year T-Note Futures
4    ZF=F  Five-Year US Treasury Note Futu
5    ZT=F            2-Year T-Note Futures
6    GC=F                             Gold
7   MGC=F               Micro Gold Futures
8    SI=F                           Silver
9   SIL=F             Micro Silver Futures
10   PL=F                         Platinum
11   HG=F                           Copper
12   PA=F                        Palladium
13   CL=F                        Crude Oil
14   HO=F                      Heating Oil
15   NG=F                      Natural Gas
16   RB=F                    RBOB Gasoline
17   BZ=F  Brent Crude Oil Last Day Financ
18   B0=F  Mont Belvieu LDH Propane (OPIS)
19   ZC=F                     Corn Futures
20   ZO=F                      Oat Futures
21   KE=F             KC HRW Wheat Futures
22   ZR=F               Rough Rice Futures
23   ZM=F             Soybean Meal Futures
24   ZL=F              Soybean Oil Futures
25   ZS=F                  Soybean Futures
26   GF=F            Feeder Cattle Futures
27   HE=F                Lean Hogs Futures
28   LE=F              Live Cattle Futures
29   CC=F                            Cocoa
30   KC=F                           Coffee
31   CT=F                           Cotton
32  LBS=F     Random Length Lumber Futures
33   OJ=F                     Orange Juice
34   SB=F                            Sugar

In [20]:
tickers = df["Symbol"]
for t in tickers:
    cur = yf.Ticker(t)
    hist = cur.history(period="max", actions=False)
    hist.to_csv('{}.csv'.format(t))