In [2]:
import yfinance as yf
import pandas as pd

In [6]:

FC_F = yf.Ticker("BTC-USD")
hist = FC_F.history(period="max")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800,0,0
2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200,0,0
2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700,0,0
2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600,0,0
2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100,0,0
...,...,...,...,...,...,...,...
2022-06-22,20719.414062,20835.750000,19848.078125,19987.029297,28574793478,0,0
2022-06-23,19986.607422,21135.761719,19950.117188,21085.876953,26188097173,0,0
2022-06-24,21084.648438,21472.917969,20777.511719,21231.656250,24957784918,0,0
2022-06-25,21233.609375,21520.914062,20964.585938,21502.337891,18372538715,0,0
2022-06-26,21471.253906,21773.453125,21179.734375,21375.744141,17422835712,0,0

In [17]:
df = pd.read_csv("_meta.txt")
df

   Symbol                             Name
0    NQ=F                       Nasdaq 100
1   RTY=F  E-mini Russell 2000 Index Futur
2    ZB=F       U.S. Treasury Bond Futures
3    ZN=F           10-Year T-Note Futures
4    ZF=F  Five-Year US Treasury Note Futu
5    ZT=F            2-Year T-Note Futures
6    GC=F                             Gold
7   MGC=F               Micro Gold Futures
8    SI=F                           Silver
9   SIL=F             Micro Silver Futures
10   PL=F                         Platinum
11   HG=F                           Copper
12   PA=F                        Palladium
13   CL=F                        Crude Oil
14   HO=F                      Heating Oil
15   NG=F                      Natural Gas
16   RB=F                    RBOB Gasoline
17   BZ=F  Brent Crude Oil Last Day Financ
18   B0=F  Mont Belvieu LDH Propane (OPIS)
19   ZC=F                     Corn Futures
20   ZO=F                      Oat Futures
21   KE=F             KC HRW Wheat Futures
22   ZR=F               Rough Rice Futures
23   ZM=F             Soybean Meal Futures
24   ZL=F              Soybean Oil Futures
25   ZS=F                  Soybean Futures
26   GF=F            Feeder Cattle Futures
27   HE=F                Lean Hogs Futures
28   LE=F              Live Cattle Futures
29   CC=F                            Cocoa
30   KC=F                           Coffee
31   CT=F                           Cotton
32  LBS=F     Random Length Lumber Futures
33   OJ=F                     Orange Juice
34   SB=F                            Sugar

In [20]:
tickers = df["Symbol"]
for t in tickers:
    cur = yf.Ticker(t)
    hist = cur.history(period="max", actions=False)
    hist.to_csv('{}.csv'.format(t))